@if(Request::root() == 'https://www.atgames.net' || Request::root() == 'http://acnet-lb.atgames.net' || Request::root() == 'https://acnet-lb.atgames.net')
    <div class="filteraz-inner">
        <a class="filteraz-link @if($prefix == '') active @endif" href="{{ @$url_action }}?series={{ @$series }}&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">Show All</a>
        <a class="filteraz-link @if($prefix == 'A') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=A&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">A</a>
        <a class="filteraz-link @if($prefix == 'B') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=B&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">B</a>
        <a class="filteraz-link @if($prefix == 'C') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=C&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">C</a>
        <a class="filteraz-link @if($prefix == 'D') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=D&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">D</a>
        <a class="filteraz-link @if($prefix == 'E') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=E&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">E</a>
        <a class="filteraz-link @if($prefix == 'F') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=F&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">F</a>
        <a class="filteraz-link @if($prefix == 'G') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=G&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">G</a>
        <a class="filteraz-link @if($prefix == 'H') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=H&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">H</a>
        <a class="filteraz-link @if($prefix == 'I') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=I&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">I</a>
        <a class="filteraz-link @if($prefix == 'J') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=J&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">J</a>
        <a class="filteraz-link @if($prefix == 'K') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=K&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">K</a>
        <a class="filteraz-link @if($prefix == 'L') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=L&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">L</a>
        <a class="filteraz-link @if($prefix == 'M') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=M&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">M</a>
        <a class="filteraz-link @if($prefix == 'N') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=N&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">N</a>
        <a class="filteraz-link @if($prefix == 'O') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=O&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">O</a>
        <a class="filteraz-link @if($prefix == 'P') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=P&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">P</a>
        <a class="filteraz-link @if($prefix == 'Q') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=Q&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">Q</a>
        <a class="filteraz-link @if($prefix == 'R') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=R&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">R</a>
        <a class="filteraz-link @if($prefix == 'S') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=S&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">S</a>
        <a class="filteraz-link @if($prefix == 'T') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=T&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">T</a>
        <a class="filteraz-link @if($prefix == 'U') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=U&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">U</a>
        <a class="filteraz-link @if($prefix == 'V') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=V&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">V</a>
        <a class="filteraz-link @if($prefix == 'W') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=W&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">W</a>
        <a class="filteraz-link @if($prefix == 'X') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=X&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">X</a>
        <a class="filteraz-link @if($prefix == 'Y') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=Y&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">Y</a>
        <a class="filteraz-link @if($prefix == 'Z') active @endif" href="{{ @$url_action }}?series={{ @$series }}&prefix=Z&order={{ @$order }}&friends={{ @$friends }}&rule={{ @$rule }}&table={{ @$table }}&table_rule={{ @$table_rule }}">Z</a>
    </div>
@else
    <div class="filteraz-inner">
        <a class="filteraz-link @if($prefix == '') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">Show All</a>
        <a class="filteraz-link @if($prefix == 'A') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'A', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">A</a>
        <a class="filteraz-link @if($prefix == 'B') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'B', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">B</a>
        <a class="filteraz-link @if($prefix == 'C') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'C', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">C</a>
        <a class="filteraz-link @if($prefix == 'D') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'D', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">D</a>
        <a class="filteraz-link @if($prefix == 'E') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'E', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">E</a>
        <a class="filteraz-link @if($prefix == 'F') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'F', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">F</a>
        <a class="filteraz-link @if($prefix == 'G') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'G', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">G</a>
        <a class="filteraz-link @if($prefix == 'H') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'H', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">H</a>
        <a class="filteraz-link @if($prefix == 'I') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'I', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">I</a>
        <a class="filteraz-link @if($prefix == 'J') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'J', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">J</a>
        <a class="filteraz-link @if($prefix == 'K') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'K', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">K</a>
        <a class="filteraz-link @if($prefix == 'L') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'L', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">L</a>
        <a class="filteraz-link @if($prefix == 'M') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'M', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">M</a>
        <a class="filteraz-link @if($prefix == 'N') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'N', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">N</a>
        <a class="filteraz-link @if($prefix == 'O') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'O', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">O</a>
        <a class="filteraz-link @if($prefix == 'P') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'P', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">P</a>
        <a class="filteraz-link @if($prefix == 'Q') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'Q', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">Q</a>
        <a class="filteraz-link @if($prefix == 'R') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'R', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">R</a>
        <a class="filteraz-link @if($prefix == 'S') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'S', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">S</a>
        <a class="filteraz-link @if($prefix == 'T') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'T', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">T</a>
        <a class="filteraz-link @if($prefix == 'U') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'U', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">U</a>
        <a class="filteraz-link @if($prefix == 'V') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'V', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">V</a>
        <a class="filteraz-link @if($prefix == 'W') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'W', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">W</a>
        <a class="filteraz-link @if($prefix == 'X') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'X', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">X</a>
        <a class="filteraz-link @if($prefix == 'Y') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'Y', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">Y</a>
        <a class="filteraz-link @if($prefix == 'Z') active @endif" href="{!! action(@$url_action, array('series' => @$series, 'prefix' => 'Z', 'order' => @$order, 'friends' => @$friends, 'rule' => @$rule, 'table' => @$table, 'table_rule' => @$table_rule)) !!}">Z</a>
    </div>
@endif